### ISSUE TITLE
NoMethodError: undefined method `find_or_create_by_name_and_resource_type_and_resource_id''

### ISSUE THREAD

**Issue by hiteshtr** [RolifyCommunity/rolify#136]
I used the rolify tutorial and after creating the user in console, I tried to run the command user.add_role "admin" but this is command gives following error

NoMethodError: undefined method `find_or_create_by_name_and_resource_type_and_resource_id' for Role:Module
    from /var/lib/gems/1.9.1/gems/rolify-3.2.0/lib/rolify/adapters/active_record/role_adapter.rb:12:in`find_or_create_by'
    from /var/lib/gems/1.9.1/gems/rolify-3.2.0/lib/rolify/role.rb:12:in `add_role'
    from (irb):5
    from /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in`start'
    from /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
    from /var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:41:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by forever-sumit** [comment]
Hi @EppO,
I also have the same issue. its resolved with your solution. but could you please let me know why we need to use git url. I think it is your forked repo. I don't want to clone this gem in my gemset from another repo.

Is the master branch of this gem not updated?

**Comment by wldcordeiro** [comment]
@forever-sumit That post was from over a year ago. Install the newest version of Rolify from Rubygems and if you have the issue open a new one. The original creator has closed this.

**Comment by forever-sumit** [comment]
thanks for your response 
I have used 

    gem 'rolify'

ok I am going to open a new issue
