### ISSUE TITLE
use of dynamic finders defines respond_to? method

### ISSUE THREAD

**Issue by gitgary** [RolifyCommunity/rolify#158]
This problem has a simple solution -- keep 'config.use_dynamic_shortcuts' commented out in the initializer, but I thought I would at least pass on the info.

When one turns on dynamic finders, it defines a 'respond_to?' method which conflicts with a method of the same named used within other gems like 'socialization'.  The result is that the  'rolify' version of respond_to? gets called and causes the other code to fail.  

Sorry, but I'm not precisely sure what the best way to fix this myself otherwise, I'd submit some code, but I wanted to let you know.

**Comment by Alxzu** [comment]
Hi, it seems I'm getting the same error here, can you tell me where I have to put the override code for respond_to? thank you
