### ISSUE TITLE
uninitialized constant Rolify (NameError)

### ISSUE THREAD

**Issue by Seaborg** [RolifyCommunity/rolify#185]
Rails 3.2.13
Rolify (3.3.0.rc4)
in Production ENV:
uninitialized constant Rolify (NameError)
in develpment env it is ok

**Comment by keerthivasan-d** [comment]
ruby 2.2.4
rails 4.2.4
rolify 5.1.0
Same Issue any solution?

**Comment by morissetcl** [comment]
same issue when I try to deploy on Heroku, someone find a solution ?

**Comment by keerthivasan-d** [comment]
@morissetcl just stop and start ur rails server(no restart - stop and start) .. Happy Coding 👍

**Comment by morissetcl** [comment]
Arf shame on me..thx it's works now @keerthivasan-d
