### ISSUE TITLE
Rolify initializer causings assets:precompile to fail.

### ISSUE THREAD

**Issue by brett-richardson** [RolifyCommunity/rolify#221]
Hi.

I noticed that as soon as I add the Rolify initializer an empty call to `Rolify.configure do ; end` then Heroku will fail to compile assets on a new Heroku app.

Rails 4. I have set `config.assets.initialize_on_precompile = false` and enabled `heroku labs:enable user-env-compile` but it still seems to cause this error.

**Comment by dmitrym0** [comment]
This doesn't seem to be in the latest release (4.1.1) and this pull request  #222 claims it's been merged. Any thoughts?

**Comment by EppO** [comment]
Looks like this [PR](https://github.com/RolifyCommunity/rolify/commit/840596b51b8124a10696d905483b1ab7d9064f61) reverted #222 
I did a quick test on my side, setting up a new [Rails 4.2.4 app](https://github.com/EppO/heroku-rolify) on heroku with rolify (4.1.1) and it didn't fail on precompile task
```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        I, [2015-10-15T17:40:53.802061 #1023]  INFO -- : Writing /tmp/build_812a859348373096c282658e41fb6a6f/public/assets/application-08a19ba96489d7fc7864bb409a6841003509fe519cbd091b7a11a1acc7e53fbb.js
remote:        I, [2015-10-15T17:40:53.810814 #1023]  INFO -- : Writing /tmp/build_812a859348373096c282658e41fb6a6f/public/assets/application-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css
remote:        Asset precompilation completed (3.79s)
```
Can you show a sample app that reproduces the issue?

**Comment by dmitrym0** [comment]
Odd. Right now, asset precompilation fails in `user.rb`'s `rolify` statement. If I comment it out everything is fine. I'll try to prepare a package for you tomorrow when I have some time.

**Comment by EppO** [comment]
Are you using Rails 3? Heroku mentioned a Rails 3.x specific config to not initialize the app when running the `assets:precompile` task: https://devcenter.heroku.com/articles/rails-asset-pipeline#troubleshooting

**Comment by dmitrym0** [comment]
Nope, I'm on rails 4.2.1. I saw that when googling, but it's a Rails 3 only flag.

**Comment by fabn** [comment]
Same issue here with Rails 4.2.4 and rolify 4.1.1

**Comment by dmitrym0** [comment]
@fabn, here's a work around I employed:

in `config/initializers/precompile.rb`

```
# precompile issue workaround http://stackoverflow.com/a/24887827/38753
module Precompile
  # Public: ignore the following block during rake assets:precompile
  def self.ignore
    unless ARGV.any? { |e| e == 'assets:precompile' }
      yield
    else
      line = caller.first
      puts "**** Ignoring line '#{line}' during precompile"
    end
  end
end
```

in ` app/models/user.rb`

    Precompile.ignore { rolify }

This is less than satisfying though.

**Comment by fabn** [comment]
@dmitrym0 nice solution, however it won't work when using spring gem because ARGV is empty in that case. I did something more brutal in my rolify initializer.

```ruby
begin
  Rolify.configure do |config|
    # By default ORM adapter is ActiveRecord. uncomment to use mongoid
    # config.use_mongoid

    # Dynamic shortcuts for User class (user.is_admin? like methods). Default is: false
    # config.use_dynamic_shortcuts
  end
rescue PG::ConnectionBad
  # Don't care, this may happen when precompiling assets, see https://github.com/RolifyCommunity/rolify/issues/221
end
```

Looking to a long term solution. 

BTW `connected?` is not be a good idea as stated in 840596b51b8124a10696d905483b1ab7d9064f61 comment, because database may not be already connected when that code is executed.

While digging through this issue I found the same issue in airblade/paper_trail#636 and attr-encrypted/attr_encrypted#160 maybe [this solution is good](https://github.com/attr-encrypted/attr_encrypted/pull/160/files#diff-a469a309f6fa5bb5d23e5d0c2c8de65fR61), asking @cherimarie who did the revert.

In any case I think this issue should be kept open because it exists in current codebase. 

cc @EppO
