### ISSUE TITLE
Rolify 3.4.0 adding role when calling has_role?

### ISSUE THREAD

**Issue by adambarthelson** [RolifyCommunity/rolify#225]
I've spent a few days trying to figure this out, but I've found that after an update from 3.2.0 to 3.4.0, whenever any of my after_create callbacks for the user call has_role?, it will add the role to the user as well.

With Rolify 3.4.0:

In an after_create method (this is called twice between 2 seperate methods): 
```
if self.has_role? :coach
   ...
end
```
After the user is created, checking the roles I find:

```
>> user.roles
 
=> [
    [0] #<Role:0x007fde2e68f6f0> {
                   :id => 2,
                 :name => "coach",
          :resource_id => nil,
        :resource_type => nil,
           :created_at => Wed, 22 Jan 2014 15:42:33 UTC +00:00,
           :updated_at => Wed, 22 Jan 2014 15:42:33 UTC +00:00
    },
    [1] #<Role:0x007fde2e68efc0> {
                   :id => 2,
                 :name => "coach",
          :resource_id => nil,
        :resource_type => nil,
           :created_at => Wed, 22 Jan 2014 15:42:33 UTC +00:00,
           :updated_at => Wed, 22 Jan 2014 15:42:33 UTC +00:00
    }
]
```

With Rolify 3.2.0:

After user creation (correct behavior):

```
>> user.roles
=> []
```

This bug causes issues for other users who look to signup as other roles, as the views have elements that are only shown to users with specific roles.

I'm locking my gem at 3.2.0 for now.

**Comment by EppO** [comment]
dup of #228 which includes a workaround
