### ISSUE TITLE
Rolify + Rails 4.1.0 rc2 -- [WARN] table 'Role' doesn't exist. Did you run the migration ? Ignoring rolify config.

### ISSUE THREAD

**Issue by irobayna** [RolifyCommunity/rolify#241]
On Rails 4.1.0 rc2 I get this warning

`[WARN] table 'Role' doesn't exist. Did you run the migration ? Ignoring rolify config.`

problem seems to originate here
`rolify / lib / rolify / configure.rb` 

```
def sanity_check(role_cnames)
      role_cnames = [ "Role" ] if role_cnames.empty?
      role_cnames.each do |role_cname|
        role_class = role_cname.constantize
        if role_class.superclass.to_s == "ActiveRecord::Base" && role_table_missing?(role_class)
          warn "[WARN] table '#{role_cname}' doesn't exist. Did you run the migration ? Ignoring rolify config."
          return false
        end
      end
      true
    end
```

**Comment by brxue** [comment]
Hi,

I encounter the same warning when doing 'rake db:setup' after 'rake dp:drop'.

I noted that there is a post in StackOverflow, http://stackoverflow.com/questions/23286906/rolify-tables-are-not-getting-created, which mentions that the warning is caused by improper file naming, but I checked my migrations file, it already has the correct *.rb suffix.

@irobayna, how did you solve this problem?

My version is rails 4.1.8, rolify 4.0.0

Thanks!
Brian

**Comment by brxue** [comment]
By the way, I remembered that this warning seems already existed when rolify was installed to my project.

**Comment by markalanevans** [comment]
Any updates here?

**Comment by npearson72** [comment]
Is there a reason this was closed? I'm stilling seeing the message in Rails 4.2.1

**Comment by wldcordeiro** [comment]
@npearson72 I don't know, the creator of the issue closed it. Can you provide a stack trace and/or open a  new issue if the cause differs?

**Comment by rsprabery** [comment]
Similar issue here. Went to upgrade rolify during an upgrade to Rails 4.1 and can't seem to get the table to create.

`[WARN] table 'Role' doesn't exist. Did you run the migration ? Ignoring rolify config.` -  gets printed when I run rake:test

and a summarized version of the stack trace error from failed tests: 

```
NoMethodError: undefined method `name' for nil:NilClass
... (lots of active record issues) ...
gems/rolify-4.0.0/lib/rolify/role.rb:19:in `add_role'
```

**Comment by rschooley** [comment]
Can confirm this still happens, should be reopened.

**Comment by Theminijohn** [comment]
Still happening on my end, any updates on this?

**Comment by Salinn** [comment]
Just had this occur as well

**Comment by mejiaro** [comment]
Still happening.

**Comment by aaronpark** [comment]
Still happening in rails 4.2.5 and Rolify 5.0.0
```
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'myapp_development.roles' doesn't exist: SELECT `roles`.* FROM `roles`
```

**Comment by aaronpark** [comment]
I fixed my issue by commenting out the devise line in my users model before running the migraine script.

```
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
```

after the migration worked, I uncommented the line again. fixed it up.

**Comment by JeansReal** [comment]
Any update?

**Comment by daveokeeffe** [comment]
Also seeing this in a brand new project with devise.

Commenting the rolify line in the model let me run the migration.  So the model is demanding that all habtm tables exist, which stops the migration from running.
