### ISSUE TITLE
Resource.applied_roles incorrect when User has resourcify and rolify

### ISSUE THREAD

**Issue by benmaher** [RolifyCommunity/rolify#244]
`applied_roles` in `resource.rb` relies upon `self.roles`. Based on the example setup described and linked in this comment https://github.com/EppO/rolify/issues/102#issuecomment-11249510, method `rolify` sets `self.roles` to user instance roles. Therefore, `applied_roles` returns the combination of the user instance roles and the resource class roles instead of the resource instance roles and the resource class roles.

To test:

    class User < ActiveRecord::Base
      resourcify :resources
      rolify

In console:

    user.add_role :generic_role
    user.applied_roles

This will return:

    [#<Role id: 123, name: "generic_role", resource_id: nil, resource_type: nil, created_at: "2014-04-13 00:51:14", updated_at: "2014-04-13 00:51:14">]

which is incorrect as it is a role granted to a user but not a role that has been attached to  the user resource.

**Comment by saizai** [comment]
#245 still broken. See https://github.com/RolifyCommunity/rolify/pull/245#issuecomment-71744855
