### ISSUE TITLE
roles_name not work for mongoid

### ISSUE THREAD

**Issue by jadeydi** [RolifyCommunity/rolify#259]
lib/rolify/role.rb line 65
 def roles_name
    self.roles.select(:name).map { |r| r.name }
 end

In mongoid use 'only' to return specific fields on query and 'select' is another key works for query.

**Comment by flydrago** [comment]
I has the same issue，and  i advise.
```
def roles_name
  self.roles.pluck(:name)
end
```
this support activierecord and mongid.

**Comment by thomas-mcdonald** [comment]
Appreciate this is an old issue, I believe this is fixed on master
