### ISSUE TITLE
PG::DatatypeMismatch: ERROR: argument of AND must be type boolean, not type record

### ISSUE THREAD

**Issue by vladimirbazhanov** [RolifyCommunity/rolify#260]
Hi! I cant' fix error from issue title, may be you can help :) Here is detailed description:

I have two models in Rails 4.0.5 application, User and Company. User has 'rolify', Company has 'resourcify'. I have two pages, first page should have a list of companies current user belongs to. 'Belongs to' means that user has one or more roles for that company. For example:

```
@companies = Company.with_role([:owner, :client, :manager], current_user)
```

It works good, generate correct SQL query.

At second page I want to get list of Users like this:

```
@users = User.with_role([:owner, :client, :manager] , @company)
```

So, I want to get all users with that roles for given company.

But I get error: 

```
ActiveRecord::StatementInvalid - PG::DatatypeMismatch: ERROR:  argument of AND must be type boolean, not type record
```

Here is SQL query that raises error:

```
"SELECT "users".* FROM "users" INNER JOIN "users_roles" ON "users_roles"."user_id" = "users"."id" INNER JOIN "roles" ON "roles"."id" = "users_roles"."role_id" WHERE ((((roles.name = 'owner','employee','client') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)) OR ((roles.name = 'owner','employee','client') AND (roles.resource_type = 'Company') AND (roles.resource_id IS NULL)) OR ((roles.name = 'owner','employee','client') AND (roles.resource_type = 'Company') AND (roles.resource_id = 3))))"
```

So, questions are: is it bug? may be I'm doing something wrong? How can I get users with given array of roles? 
Btw, query like

```
User.with_role(:owner, @company)
```

works, but returns duplicates (for eg, it returns 2 users when there is only one owner and only one user in database.

Thanks for any help or ideas :)

Regards, Vladimir

**Comment by gabrielhilal** [comment]
I'm facing the same problem with `4.1.1`.

**Comment by wldcordeiro** [comment]
@gabrielhilal Could I get more details on your stack? Ruby version, Rails version, PostgreSQL version or any other information that might help? I haven't seen this error before in my use and the OP never responded.

**Comment by gabrielhilal** [comment]
ruby `ruby 2.2.2p95`
rails `4.2.3`
PostgreSQL `9.4.0`

I believe `with_role` is expecting only one role and not an array of roles... It might be the expected behaviour (not sure), but I could not find any helper to return all users for a given `instance` and many roles.

I was looking for something like:

```
User.joins(:roles)
  .where(roles: { name: [:admin, :super],
                          resource_type: 'Account',
                          resource_id: Account.first }
              ).uniq
```

**Comment by wldcordeiro** [comment]
@gabrielhilal It does appear that `with_role` expects a single role and not an array. This may be something that could be changed though. Here's the definition of it.
https://github.com/RolifyCommunity/rolify/blob/master/lib/rolify/finders.rb#L3
```rb
    def with_role(role_name, resource = nil)
      self.adapter.scope(self, :name => role_name, :resource => resource)
    end
```

**Comment by wldcordeiro** [comment]
You may want to try `with_all_roles` or `with_any_role`

**Comment by gabrielhilal** [comment]
Thanks @wldcordeiro, but `with_any_role` and `with_all_roles` does not accept the `resource`, right?
So, how can I simple list all users that have any role in an `instance`?

**Comment by werleo** [comment]
@gabrielhilal actually you may pass many hashes to ```with_all_roles``` like this:

```
User.with_all_roles({name: :owner, resource: @company}, {name: :client, resource: @company }, {name:  :manager, resource: @company})
```

**Comment by EppO** [comment]
Indeed, `with_all_roles` is the way to go. closing
