### ISSUE TITLE
resourcify with custom role_cname fail

### ISSUE THREAD

**Issue by ledowong** [RolifyCommunity/rolify#290]
https://github.com/RolifyCommunity/rolify/wiki/Configuration

Follow the document, I added:
resourcify :role_cname => 'UserRole'

but it fail to load.

I trace the code and found:
https://github.com/RolifyCommunity/rolify/blob/master/lib/rolify.rb#L41
there is a association_name which doesn't mention in the wiki.

Look like this works for me:
resourcify :user_roles, :role_cname => 'UserRole'

We should update the wiki or update the code?

**Comment by EppO** [comment]
[Wiki](https://github.com/RolifyCommunity/rolify/wiki/Configuration#configure-your-resource-models) has been updated accordingly, thanks.
