### ISSUE TITLE
Warning when I add rolify method to admin model

### ISSUE THREAD

**Issue by mintuhouse** [RolifyCommunity/rolify#298]
````
class Admin < ActiveRecord::Base
  rolify

  ....
end
````
When I add rolify method to Admin model and run db:migrate, I get these warnings. Am I doing something wrong?
````
/gems/activerecord-4.1.8/lib/active_record/associations.rb:1585: warning: already initialized constant Admin::HABTM_Roles
/gems/activerecord-4.1.8/lib/active_record/associations.rb:1585: warning: previous definition of HABTM_Roles was here
````

**Comment by sazzadNascenia** [comment]
Did You people find any solution of this problem ?

**Comment by wldcordeiro** [comment]
@sazzadNascenia It isn't really a problem per se, it's a warning. It's not a super high priority currently but I'm investigating its source.

**Comment by mihael** [comment]
`/gems/activerecord-4.2.0/lib/active_record/associations.rb:1693: warning: previous definition of HABTM_Roles was here`
