### ISSUE TITLE
Role is totally removed if removed from one of user model

### ISSUE THREAD

**Issue by shir** [RolifyCommunity/rolify#306]
I have to user models `User1` and `User2`. Both use rolify. Users from both model have same role:
```rb
user1.add_role :admin
user2.add_role :admin
```
If I remove role for `user2` and there is no other users of model `User2` with same role then role will be totally removed:
```rb
user2.remove_role :admin
user1.reload
user1.has_role? :admin # => false
```

**Comment by wldcordeiro** [comment]
Is this still present in version 3.5.2? @shir

**Comment by shir** [comment]
@wldcordeiro Sorry, I can't check because we stopped to use this gem our project.

**Comment by jamebar** [comment]
Hi, we're using 4.0 and still seeing this happening.  If we remove_role from a user and there aren't any other users currently using that role, then the role gets totally removed from the database.

**Comment by EppO** [comment]
@jamebar: set `remove_role_if_empty` to false in the `Rolify.configure` block to keep the role instead.

**Comment by daslicious** [comment]
the role still gets removed even if the role is still being used.  and should we have to set the config to avoid this behavior?

**Comment by aliyazdani** [comment]
I'm using v 5.0.0 and this issue still exists.  Instead of 'remove_role' which removes the actual role from the 'roles' table, I just wrote a quick method to remove the row in the join table.
