### ISSUE TITLE
ActiveRecord::RecordInvalid: Validation failed: Resource type is not included in the list

### ISSUE THREAD

**Issue by sazzadNascenia** [RolifyCommunity/rolify#311]
Hello ,
I am getting this problem when I am trying to add a role from rails console.
Does anyone have faced this problem ? I am stuck with for hours.
 u = User.first
 u.add_role(:admin).save!
ActiveRecord::RecordInvalid: Validation failed: Resource type is not included in the list.

Gem version ======  rolify 3.5.0

Rolify migration file ============
class RolifyCreateRoles < ActiveRecord::Migration
  def change
    create_table(:roles) do |t|
      t.string :name
      t.references :resource, :polymorphic => true
      t.timestamps
    end

    create_table(:users_roles, :id => false) do |t|
      t.references :user
      t.references :role
    end

    add_index(:roles, :name)
    add_index(:roles, [ :name, :resource_type, :resource_id ])
    add_index(:users_roles, [ :user_id, :role_id ])
  end
end
================

**Comment by lesterchan** [comment]
Yeap same case as #310

**Comment by wldcordeiro** [comment]
Since this is a duplicate and #310 is closed I'm closing this as well. If it is still present please reopen.
