### ISSUE TITLE
with_groups raises MySQL error: "Operand should contain 1 column(s)"

### ISSUE THREAD

**Issue by ngw** [RolifyCommunity/rolify#312]
I've just updated from rolify 3.4.0 to rolify 3.5.2 and I'm having some problems with MySQL.

https://gist.github.com/ngw/a3146ed2ce238226c993

This is what's inside Role::NAMES, a simple Array:

    2.1.3 :011 >   Role::NAMES
     => ["approver", "rejecter", "approve_all", "poster", "replier", "tagger", "issuer", "grouper", "tags_manager", "issues_manager", "groups_manager", "alerts_manager", "users_manager", "brands_manager", "customers_manager", "authors_manager", "lists_manager"]

And here is the "u":

    2.1.3 :012 > u.inspect
     => "#<User id: 4, first_name: \"User\", last_name: \"User\", email: \"something@thefool.it\", customer_id: 1, quick_moderation: true, encrypted_password: \"$2a$10$qxjudWwPsy.N1ExYIIBGcuOi8aR0244TuRjB0a.4yvr...\", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 211, ....>"

What is the problem here?

**Comment by wldcordeiro** [comment]
Can you paste the traceback as well?

**Comment by ngw** [comment]
Isn't it inside the gist? Which one?

**Comment by ngw** [comment]
If it helps here is my Gemfile.lock - quite stuck right now

**Comment by wldcordeiro** [comment]
I'm investigating the issue now to see if it is present in the gem for all databases or if it may be a MySQL issue.

**Comment by ngw** [comment]
Any workaround?

**Comment by ngw** [comment]
If it's MySQL the problem is on both 5.5.41 I have in production and 5.6.22 I have in local. Seems very unlikely to me...

**Comment by ngw** [comment]
Not strictly a bug.
Ok, the problem is the SQL query which was wrong, the subquery had too many fields (https://gist.github.com/ngw/97d621f996d7123d17cc).
I had a default_scope set on the Role class, apparently everything was ok before.
