### ISSUE TITLE
Create new model based on role

### ISSUE THREAD

**Issue by gogainda** [RolifyCommunity/rolify#313]
I have model Consultant which is based on the User model

class Consultant < ActiveRecord::Base
  self.table_name = 'users'
 
end
How can I apply rule with_role(:consultant) to the entire model so User.with_role(consultant) is equale to Consultant.all?

**Comment by wldcordeiro** [comment]
I don't think you understand the aim of this project or I'm not understanding your question. You don't need to create the Consultant model.
You would add the role with `grant` or `add_role` and then to get all Users with the consultant role you use `User.with_role(:consultant)`

**Comment by gogainda** [comment]
Instead of User.with_role(:consultant) I want type only Consultant so with_role(:consultant) would be automatically applied to the user model

**Comment by wldcordeiro** [comment]
That isn't a feature of rolify. You can subclass your user model and call it Consultant then use a permissions gem like CanCanCan to give Consultants their permissions, rolify is just for setting roles. The other option is to add a named scope to your users model like 
```rb
scope :consultants, -> { User.with_role(:consultant) }
``` 
Then you can use `User.consultants` and it will return your consultants.
