### ISSUE TITLE
Avoiding duplicate role data

### ISSUE THREAD

**Issue by Elyasin** [RolifyCommunity/rolify#319]
Hi there, first of all thank you for the gem. It is very useful to me.

I noticed that I can add the same role for an instance twice, i.e. duplicates are not avoided. At the moment I have a workaround for this.

However I thought maybe there were use cases for this, since I don't see why one could have a duplicate entry for that. Or do you have a suggestion how to avoid it? Unique index or so?

I am using Rails 4.2, Mongoid, rolify with authorization.

Regards,
Ely

**Comment by andradei** [comment]
Thank you for your info. I need to do some testing to see if this behavior is just for MongoDB. Will update the thread with what I find.

**Comment by sadiqmmm** [comment]
Hi,

I am using devise gem and PostgreSQL as database.

In the User class i am calling a "after_create :assign_default_role" action as method

def assign_default_role
    add_role(:basic) if self.roles.blank?
  end

----------------------
When i am create the new user through the signup form. 
I am getting the basic role assigned twice. See the image below

Thanks

![rolify](https://cloud.githubusercontent.com/assets/672989/6895005/e2d24572-d6f8-11e4-8b63-c320b43c47cf.png)

**Comment by ewilliam** [comment]
ran into the same problem. see: #228

**Comment by EppO** [comment]
dup of #228 which includes a workaround
