### ISSUE TITLE
NoMethodError: undefined method `find_or_create_by_name_and_resource_type_and_resource_id' for #<Class:0xa484428>

### ISSUE THREAD

**Issue by forever-sumit** [RolifyCommunity/rolify#320]
I have used

    gem 'rolify'

after bundle install I have got this issue I cheked in my gem list and i found my rolify gem version is 

    rolify (3.2.0)

I have run the following installer

    rails g rolify:role Role User

Here is my User model

    class User < ActiveRecord::Base
      rolify
    end

Please let me know where I am doing wrong?

**Comment by wldcordeiro** [comment]
You should run `bundle update` and make sure you are  on version 4.0.0 and then report back here if the issue is still present.

**Comment by forever-sumit** [comment]
Okay, after `bundle update rolify` I have got the gem version `4.0.0`.

Yesterday I've created a new rails app and add the `Rolify` gem and it has installed the `rolify 3.2.0` .
today I again try with createing new rails app now it has installed `4.0.0` 

Strange, but now problem has been resolved, Thanks

**Comment by wldcordeiro** [comment]
You're welcome! Enjoy using Rolify. :smile:
