### ISSUE TITLE
Dynamic roles?

### ISSUE THREAD

**Issue by quantumpotato** [RolifyCommunity/rolify#321]
Hi, does Rolify support dynamic role permissions eg. that can change at runtime?

**Comment by andradei** [comment]
Roles are attributes that can change like any other Ruby object's attribute. You might have uncertain behavior by altering roles with permissions to resources at runtime, so test your code :)

**Comment by quantumpotato** [comment]
Oh right, I was thinking of the paradigm where you add permissions to a
specific User. Thanks! #close

**Comment by wldcordeiro** [comment]
@quantumpotato Rolify doesn't handle permissions, it just sets roles and you can do instance level permission granting with a call like `User.all.first.grant(:admin)` Obviously that's a really simple example but if you can filter the user in particular you want you can just use the grant method to give them the role you want. If you want to add permissions you can integrate with the CanCan library (there's a guide in the wiki.)

**Comment by quantumpotato** [comment]
Thanks! It's been a while since I've worked with Rolify. I appreciate the
help!
