### ISSUE TITLE
User.with_role(:manager, Company.find(1)) returns duplicate when user has instance role + class role

### ISSUE THREAD

**Issue by voyera** [RolifyCommunity/rolify#324]
Hi there,

I'm not sure if the problem resides in business logic rather than how rolify is but I'm wondering if something is off.

Basically I have a User with add_role(:manager) and add_role(:manager, Company.find(1)).

I would think that User.with_role(:manager, Company.find(1)) would return the user once but he appears twice which is a bit misleading.

I'm using Rails 4.2.0 and SQLite

**Comment by wldcordeiro** [comment]
The first role you set is global and implicitly gives you the `:manager` role over Company 1. Details are in this section https://github.com/RolifyCommunity/rolify/wiki/Usage#role-queries (#4)

**Comment by voyera** [comment]
Thanks, I will mark this as closed :)
