### ISSUE TITLE
Change User.with_roles to User.with_all_roles in readme.md

### ISSUE THREAD

**Issue by deepsystm** [RolifyCommunity/rolify#325]
`User.with_roles` has been renamed to `User.with_all_roles`
change docs please.

**Comment by wldcordeiro** [comment]
Where is `with_roles` still referenced? If it's in a wiki page you're welcome to edit them.

**Comment by deepsystm** [comment]
https://github.com/RolifyCommunity/rolify#class-level
```
Forum.with_roles([:admin, :user], current_user)
# => [ list of Forum instances that has role "admin" or "user" binded to it and belongs to current_user roles ]
```

**Comment by wldcordeiro** [comment]
Ah, thank you that's in the readme, I'll fix those references.
