### ISSUE TITLE
Display all of a users Roles - Multiple roles

### ISSUE THREAD

**Issue by DigitalRecline** [RolifyCommunity/rolify#340]
Just wondering how to get a record of all roles a user has.

currently using this but it only takes the first role it finds. Not sure how to get it to find all the roles. Or the correct loop to have it get all the roles. Any help would be great.

    <ul>
     <table class="table-bordered col-md-6 ">
           <% @users.each do |user| %>

        <tr>
          <td><%= link_to user.email, edit_user_path(user) %></td>
                
          <td><%= user.roles.first.name %></td>

          <td><%= user.id %></td>
        </tr>
     <% end %>

      </table>
    </ul>

**Comment by adityashankert** [comment]
```
<ul>
 <table class="table-bordered col-md-6 ">
       <% @users.each do |user| %>

    <tr>
      <td><%= link_to user.email, edit_user_path(user) %></td>

      <td><%= user.roles.pluck(:name).join(",") %></td>

      <td><%= user.id %></td>
    </tr>
 <% end %>

  </table>
</ul>
```

**Comment by EppO** [comment]
@adityashankert's code should do the trick
