### ISSUE TITLE
Wiki - Passing role to callback

### ISSUE THREAD

**Issue by ashwinputhige** [RolifyCommunity/rolify#354]
In the [configuration](https://github.com/RolifyCommunity/rolify/wiki/Configuration) wiki, there is this note - 
```*PLEASE NOTE: when defining callback methods you must specify role argument,...  ``` .

In Rails 4, I actually got an error when I added the role as parameter to callback.

```
after_create :add_role_to_user
def add_role_to_user(role) ##--->ERROR
end
```
Does the wiki need updating or is it only me?

**Comment by wldcordeiro** [comment]
What was the actual error?

**Comment by ashwinputhige** [comment]
``` Wrong number of arguments (1 for 0 ) ```

**Comment by wldcordeiro** [comment]
In this section https://github.com/RolifyCommunity/rolify/wiki/Configuration#configure-your-user-model
it states that the options that are accepted are 

* before_add
* after_add
* before_remove
* after_remove

and you're trying with after_create.

**Comment by ashwinputhige** [comment]
Oh I see now. Thanks for explaining that.
