### ISSUE TITLE
Issue with table name with Postgres schemas

### ISSUE THREAD

**Issue by jonsgreen** [RolifyCommunity/rolify#374]
We are using rolify in an application that uses the Apartment gem to set up schemas for a multitenant Rails application. It becomes important for tables that are in the public schema to be explicitly defined as such (e.g. "public"."teams"). 

We are getting SQL errors because such table names are not being correctly quoted: 
```SQL
   PG::UndefinedTable: ERROR:  relation "public.roles" does not exist
       LINE 1: ..."public.teams".* FROM "public"."teams" INNER JOIN "public.ro...
                                                                    ^
       : SELECT "public.teams".* FROM "public"."teams" INNER JOIN "public.roles" ON "public.roles".resource_type IN ('Team') AND
```
It seems like a simple fix is to use change [this method](https://github.com/RolifyCommunity/rolify/blob/master/lib/rolify/adapters/active_record/resource_adapter.rb#L47-L49) to:
```ruby
      def quote(column)
        ActiveRecord::Base.connection.quote_table_name column
      end
```
This correctly allows the underlying pg adapter to correctly quote tables with schemas (e.g. "public"."roles"). 

I have not investigated the code or specs to see what implications this change would have. Please let me know whether this solution seems suitable or whether more code changes and specs might be required for a pull request.

**Comment by jonsgreen** [comment]
@wldcordeiro :
I am just turning back to this again and realizing that there is more to this issue. When using the Apartment gem with postgres adapter certain models can be kept in the public schema while others are added to 'tenant' schemas. In our case we have Role as an excluded model which keeps it in the public schema. So really it is also important that table_names get prefixed correctly with their schemas otherwise the search path does not find the roles in the public schema. Apartment gem relies on ActiveRecord table_name class methods to get this right and I would suggest that you consider doing this as well. So for example in the resourcify method [here](https://github.com/RolifyCommunity/rolify/blob/master/lib/rolify.rb#L49) perhaps just:
```
self.role_table_name = self.role_cname.constantize.table_name 
```
I am guessing there may be reasons for not doing it this way. Perhaps it doesn't work for all adapters and there may be other situations like in rolify method where the code would need to be more thoughtful in order to generate join table names. Anyhow, just thought I would add a comment and leave it to you whether to open this ticket again. 

Also if someone else runs into this issue there is a simple work around of adding this line to your ActiveRecord model if you are not getting the results you expect:

```
resourcify
self.role_table_name = ::Role.table_name
```

**Comment by samuelpares** [comment]
Still having this issue.
Thanks to @jonsgreen previous answer I could make it work.
Is this the right approach yet?
