### ISSUE TITLE
has_role method without question sign cause adding a role

### ISSUE THREAD

**Issue by pavelkvasnikov** [RolifyCommunity/rolify#377]
I forgot adding a question sign at the end of the method has_role? and found that current_user now has new role instead of raising an exception or checking for that role. I know it's my mistake, but is it an expected behavior or it's a bug? 
```
current_user.has_role('Admin') # this adds new role for current_user
```

rolify (3.4.1)
rails (4.1.10)
ruby '2.1.3'

**Comment by wldcordeiro** [comment]
That is an old method name and was removed in rolify 4+ it was renamed to `add_role` or aliased as `grant`.

**Comment by MSeneadza** [comment]
Wow, I just had this problem in the current version of Rolify.  It was driving me crazy trying to track down how some of my users were becoming admins!  I see that `has_role` has been deprecated but I'm wondering if it's time to remove it / make it throw an exception.
