### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by wldcordeiro** [RolifyCommunity/rolify#385]
Looking forward, Rails 5 support is something we'll want. With users already trying to use Rolify with Rails 5 (see #381)

**Comment by mibamur** [comment]
+1

**Comment by wldcordeiro** [comment]
@mibamur Github now has built-in +1 support (the little smile next to  my comment above.) But this has actually been merged thanks to the work of @lorefnon I'll cut a release today. I got busy with work and hadn't had time.

**Comment by wldcordeiro** [comment]
@mibamur https://rubygems.org/gems/rolify/versions/5.1.0 It's out now. @lorefnon @DmitryKK Thanks for the additions guys. :+1:
