### ISSUE TITLE
rails g rolify Role User -o mongoid

### ISSUE THREAD

**Issue by jamesaduke** [RolifyCommunity/rolify#390]
when i run this command
rails g rolify Role User -o mongoid 
 i keep getting this error
in `const_get': uninitialized constant User (NameError)

**Comment by lorefnon** [comment]
You will need to have a User class already defined in your application.

User management is not something Rolify handles. However rolify does work well with authorization solutions like [Devise](https://github.com/plataformatec/devise) which can generate a User class for you.

**Comment by jamesaduke** [comment]
Thanks
