### ISSUE TITLE
user.add_role :admin Unknown Key Error

### ISSUE THREAD

**Issue by JohnOHFS** [RolifyCommunity/rolify#392]
I'm attempting to setup rolify and I'm running into an issue assigning a role to a user in the console.  

Here's my error: 
2.2.1 :007 > user.add_role :admin
ArgumentError: Unknown key: :optional.

I'm running devise with cancancan and rolify.  I'm also running the Koudoku gem for subscription payment support.  I'm suspecting this error might be caused by the fact that my "subscriptions" table also has a "user_id" column.  Is there anything I can do to correct this issue?

Thanks.

**Comment by stephen-puiszis** [comment]
Also getting this

**Comment by JohnOHFS** [comment]
Here's the solution @stephen-puiszis http://stackoverflow.com/questions/36144877/rolify-table-error-user-add-role-admin-unknown-key-error/36151534#36151534
