### ISSUE TITLE
undefined local variable or method `rolify' for User

### ISSUE THREAD

**Issue by vjustov** [RolifyCommunity/rolify#418]
Hello, thank you for the wonderful work, I'm using Rolify with AR in a rails app and suddenly this error started appearing in a commit where I only changed some js, and some other stuff unrelated to rolify. I started debugging the problem and I have isolated the problem to the one line where the Gemfile.lock changes from react-rails from `react-rails (1.1.0)` to `react-rails (1.8.2)`.

I'm using  ruby 2.3.1, rails 4.2.7.1 and rolify 5.1.0. Sadly I couldn't replicate the issue with a new app.
In [this gist](https://gist.github.com/vjustov/0f117d1b097960085849809ed36e22cf) you can see the conflicting gemfile and gemfile.lock.

Let me know if i need to supply more info.

**Comment by vjustov** [comment]
I fixed the problem by reordering my gemfile, `gem "rolify"` before `gem "react-rails"`... now the question remains: 
![giphy 1](https://cloud.githubusercontent.com/assets/4332586/18652691/75e02f44-7ea2-11e6-859e-935f3ba72d5d.gif)

**Comment by cipater** [comment]
Ran into the same issue after upgrading an existing app from rails 4.2.8 to 5.1.0.

Reordering the Gemfile didn't do anything for my case. However, adding a `require 'rolify'` to the top of `application.rb` did the trick:

```
require File.expand_path('../boot', __FILE__)

require 'rolify'
require 'rails/all'
# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)
```

**Comment by batmanbury** [comment]
I'm using Rails 5.1.1 with rolify 5.1.0 and seem to have this same issue. None of the above suggestions worked however.

First, after bundle installing, the generators would not appear in the `rails g` list, so I added the generator files manually to `lib` and ran them with `rails g active_record:rolify Role User`. Still, no gem methods work, and going into rails console gives me `undefined local variable or method 'rolify'`

**Comment by ezetadev** [comment]
@cipater solution worked for me. Rails 5.1.2 and rolify 5.1.0.

**Comment by nickrivadeneira** [comment]
I fixed this by adding this line to `application.rb`:
```ruby
require 'rolify/railtie'
```
Reordering the Gemfile was not required. Got the idea from [here](https://github.com/RolifyCommunity/rolify/issues/156#issuecomment-23440486).

**Comment by EppO** [comment]
Added `react-rails` workaround in the [Wiki](https://github.com/RolifyCommunity/rolify/wiki/FAQ#when-i-start-rails-using-server-console-whatever-i-get-this-error)
