### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported

### ISSUE THREAD

**Issue by brandoncordell** [RolifyCommunity/rolify#444]
Rails: 5.1.0.beta1
Ruby: 2.4.0
Rolify: 5.1.0

This generated migration fails on this version of rails

```
  class RolifyCreateRoles < ActiveRecord::Migration
    def change
      ...
    end
  end
```

```
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class RolifyCreateRoles < ActiveRecord::Migration[4.2]
/Users/brandoncordell/Code/dsk_group/db/migrate/20170307143104_rolify_create_roles.rb:1:in `<top (required)>'
/Users/brandoncordell/Code/dsk_group/bin/rails:9:in `require'
/Users/brandoncordell/Code/dsk_group/bin/rails:9:in `<top (required)>'
/Users/brandoncordell/Code/dsk_group/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class RolifyCreateRoles < ActiveRecord::Migration[4.2]
/Users/brandoncordell/Code/dsk_group/db/migrate/20170307143104_rolify_create_roles.rb:1:in `<top (required)>'
/Users/brandoncordell/Code/dsk_group/bin/rails:9:in `require'
/Users/brandoncordell/Code/dsk_group/bin/rails:9:in `<top (required)>'
/Users/brandoncordell/Code/dsk_group/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Solution:** I change `class RolifyCreateRoles < ActiveRecord::Migration` to `class RolifyCreateRoles < ActiveRecord::Migration[5.0]`

**Comment by patil-gaurav** [comment]
thanks @brandoncordell

**Comment by Uriel7** [comment]
Thank u for the solution @brandoncordell

**Comment by sicaps** [comment]
@brandoncordell -- Thanks

**Comment by obfusticatedcode** [comment]
Thanks, I got the same error and adding the version solves the issue. In my case added, [5.1]

**Comment by raruhuyamato** [comment]
thanks

**Comment by AshishClecotech** [comment]
Hello @brandoncordell , I have still found the error in latest gem version of rolify.  This fix is not updated in the rolify gem ?
Please let me know

**Comment by brandoncordell** [comment]
@AshishClecotech Yeah this issue is still open. No feedback from the Rolify team about it yet. At least it's an easy fix. I haven't opened a pull request for a fix, because I'm not sure how to a) test this properly, and b) still make it backwards compatible with older versions of Rails.

**Comment by AshishClecotech** [comment]
@EppO, Should I go ahead and fix this. I will take care about the compatibility of other lower versions as well.

**Comment by goterpsgo** [comment]
I just downgraded my rails to v5.0.5 and was able to run a migration without issues. I restored my app to use v5.1.3 and it started up.

**Comment by n1ckbren** [comment]
Funny, but on 5.1.3 you still need add version to migration file.

**Comment by redtachyons** [comment]
Thanks for the tip, Here is one liner to do that

> grep -rl  "ActiveRecord::Migration"  db | xargs sed -i 's/ActiveRecord::Migration/ActiveRecord::Migration[5.1]/g'

**Comment by jermaine** [comment]
@redtachyons When running this on OSX I get the following error: 

`...extra characters at the end of d command`

To get around this I had to add an empty string to sed.

This worked for me.
`grep -rl "ActiveRecord::Migration" db | xargs sed -i "" "s/ActiveRecord::Migration/ActiveRecord::Migration[5.1]/g"`

**Comment by redtachyons** [comment]
@jermaine seems like that is a slight behavior change between Gnu sed and Bsd sed

**Comment by eriknomitch** [comment]
@jermaine Thanks. To prevent any which would already have a version tag, I changed your one-liner to the following:

```Shell
grep -rl "ActiveRecord::Migration$" . | xargs sed -i "" "s/ActiveRecord::Migration/ActiveRecord::Migration[5.1]/g"
```

Note the `$`.

**Comment by vynessa** [comment]
Thanks @brandoncordell. This fixed it for me.

**Comment by wandersonsc** [comment]
Thank you @brandoncordell! I have been scratching my head all morning trying to figure that out!
*Rails 5.1.4.

**Comment by SuelioPinho** [comment]
Thanks @brandoncordell

**Comment by LeVanVuong93** [comment]
Hi
Solution is change class RolifyCreateRoles < ActiveRecord::Migration to class RolifyCreateRoles < ActiveRecord::Migration[5.0] ?
Could you tell me how to change this ? :(

**Comment by brandoncordell** [comment]
@LeVanVuong93 When you run `rails g rolify:role Role User` to generate the Rolify migrations/configs you'll have to go into the migration and change the class definition. It will be in `db/migrate` and will be the most recent file created.

You'll see `class RolifyCreateRoles < ActiveRecord::Migration` at the top of the file. Just add `[5.0]` to the end of `ActiveRecord::Migration` and then re-run the migration.

That should do it.

**Comment by BasileM** [comment]
thanks 🙌

**Comment by EppO** [comment]
rolify 5.2 adds ActiveRecord version to the migration file:

```
class RolifyCreate<%= table_name.camelize %> < ActiveRecord::Migration<%= migration_version %>
```

**Comment by luccabb** [comment]
**To be clear on the** `Directly inheriting from ActiveRecord::Migration is not supported ` **error**


Rails 5 requires that you specify the rails version that generated the migration file. 

So if you're on any rails >= 5, your migrations file shouldn't be inheriting from `ActiveRecord::Migration`, like: 

`class AddColumnToDB < ActiveRecord::Migration`  

but they should be:

`class AddColumnToDB < ActiveRecord::Migration[rails_version_when_this_was_generated]`

So in case you are upgrading from rails 4.2 to 5, you should change all your migrations files that were made on Rails 4.2 to reflect that:

`class AddColumnToDB < ActiveRecord::Migration[4.2]` 

> You can check this and other changes on migrations if you're upgrading from rails 4 to 5 [here](https://blog.bigbinary.com/2016/03/01/migrations-are-versioned-in-rails-5.html)

**Comment by TorvaldsDB** [comment]
> @jermaine Thanks. To prevent any which would already have a version tag, I changed your one-liner to the following:
> 
> ```shell
> grep -rl "ActiveRecord::Migration$" db | xargs sed -i "" "s/ActiveRecord::Migration/ActiveRecord::Migration[5.1]/g"
> ```
> 
> Note the `$`.

niubility!

**Comment by martinbarilik** [comment]
for debian users

`p -rl "ActiveRecord::Migration$" db | xargs sed -i "s/ActiveRecord::Migration/ActiveRecord::Migration[5.1]/g"`

note "" being removed as the parameter is not supported _( -i "" )_

```
-i means in-place, that is, edit in the file directly.
-i '' means edit in place a file whose name is the empty string.
```
