### ISSUE TITLE
Rails 5 changes

### ISSUE THREAD

**Issue by SaimonL** [RolifyCommunity/rolify#459]
This could be a duplicate so feel free to close it.

In Rails 5 the polymorphic is required so if you want to create a record without setting it then set `, optional: true`

Example:
```ruby
belongs_to :roleable, polymorphic: true, optional: true
```

This will get rid off resource error

**Comment by wldcordeiro** [comment]
@SaimonL Rails 5 is not yet supported. To be honest I haven't had a chance to update the library as my career has taken me more towards the frontend and I don't work in Rails often. I'd love to get a set of additional maintainers here as the idea is that we could maintain via community.

**Comment by EppO** [comment]
Should be fixed now. Re-open if it still happens

**Comment by gastonmorixe** [comment]
@EppO adding `optional: true` to `Role` solves 300+ specs

`belongs_to :resource, :polymorphic => true, :optional => true`
