### ISSUE TITLE
[fixed] Rails 5.1.4 - User.last.roles return an error straight away.

### ISSUE THREAD

**Issue by thibaut-poullain** [RolifyCommunity/rolify#461]
### **FIXED : don't put _has_many :roles, through: :users_roles_ in your user model. Rolify already do it for you ;)**

I'm on ruby 2.4.1p111 (2017-03-22 revision 58053) and Rails 5.1.4.

I followed the getting started process and I got this error straight away :

> [1] pry(main)> User.last.roles
  User Load (0.4ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
NoMethodError: undefined method `>' for nil:NilClass
from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/reflection.rb:960:in `check_validity!'
[2] pry(main)> exit

**Same for User.last.add_role :admin**

I've got "**rollify**" in my user model, as well as "**has_many :roles, through: :users_roles**
"

In my role model :

>   has_and_belongs_to_many :users, :join_table => :users_roles
> 
>   belongs_to :resource,
>              :polymorphic => true,
>              :optional => true
> 
>   validates :resource_type,
>             :inclusion => { :in => Rolify.resource_types },
>             :allow_nil => true
> 
>   scopify

and in my migration :

>   def change
>     create_table(:roles) do |t|
>       t.string :name
>       t.references :resource, :polymorphic => true
> 
>       t.timestamps
>     end
> 
>     create_table(:users_roles, :id => false) do |t|
>       t.references :user
>       t.references :role
>     end
> 
>     add_index(:roles, :name)
>     add_index(:roles, [ :name, :resource_type, :resource_id ])
>     add_index(:users_roles, [ :user_id, :role_id ])
>   end
> 

What's happening ? :)

Thx mates.

**Comment by thibaut-poullain** [comment]
In console, User.last.add_role(:landlord) create the role in the role table, but the command line still generate the same error :

> User.last.add_role(:landlord)
>   User Load (0.7ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
>   Role Load (0.6ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."name" = $1 AND "roles"."resource_type" IS NULL AND "roles"."resource_id" IS NULL ORDER BY "roles"."id" ASC LIMIT $2  [["name", "landlord"], ["LIMIT", 1]]
>    (0.2ms)  BEGIN
>   SQL (0.7ms)  INSERT INTO "roles" ("name", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["name", "landlord"], ["created_at", "2017-09-18 09:01:11.896810"], ["updated_at", "2017-09-18 09:01:11.896810"]]
>    (0.9ms)  COMMIT
> NoMethodError: undefined method `>' for nil:NilClass
> from /usr/local/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/reflection.rb:960:in `check_validity!'

The check in the role table :

> 
> 6] pry(main)> Role.all
>   Role Load (0.3ms)  SELECT "roles".* FROM "roles"
> => [#<Role:0x007fd787800f78
>   id: 1,
>   name: "landlord",
>   resource_type: nil,
>   resource_id: nil,
>   created_at: Mon, 18 Sep 2017 09:01:11 UTC +00:00,
>   updated_at: Mon, 18 Sep 2017 09:01:11 UTC +00:00>]

**Comment by isyiwang** [comment]
How did you fix this error?
