### ISSUE TITLE
Create role  based only on instance

### ISSUE THREAD

**Issue by Kani999** [RolifyCommunity/rolify#488]
Is there an option to create roles that we can assign to instances only but not to the whole class?

I want to define a role scoped to a resource instance:
```
user = User.find(2)
user.add_role :moderator, Forum.first
```
But I want to disable defining role's scoped to a whole class
```
user = User.find(3)
user.add_role :moderator, Forum
```

Is there any way, that I can forbid the second choice?

**Comment by EppO** [comment]
Currently the only way to prevent it is through your application code. Rolify won't enforce it for you

**Comment by Kani999** [comment]
@EppO Thanks
I've already written my own library to override some actions that fit my use case.

So I'm closing the ticket.

**Comment by EppO** [comment]
Can you share your library? If it integrates with rolify, I can link it in the README like Cancan and Pundit

**Comment by Kani999** [comment]
@EppO 
I've created a repository with some description of how my library works.
It's nothing revolutionary and bullet-proof, but it's possible that it might help someone.

Here's a link https://github.com/Kani999/rolify_restrictions

**Comment by Kani999** [comment]
@EppO 
I added a docker-compose template to the repository above. So you could try the library.
Please try to run the Docker. It is my first template, so I hope it will work.
