### ISSUE TITLE
Is there a way to get role for a given user and resource ?

### ISSUE THREAD

**Issue by JonLev** [RolifyCommunity/rolify#506]
I have a given resource Foo with id 1, and users that can have distinct roles
- One can read, he has the role `reader` (let's say id 1)
- One can write, he has the role `editor` (let's say id 2)

I want to adapt my front depending of the role, so I need to find the role for Foo.find(1) like:
```
User.find(1).role_for(Foo.find(1))
# should return :reader
```

Is there a way to do so?

**Comment by EppO** [comment]
You should find everything you need in the [wiki](https://github.com/RolifyCommunity/rolify/wiki/Usage#role-queries):
```ruby
user = User.find(2)
user.add_role :reader, Foo.first # sets a role scoped to a resource
user.has_role? :reader, Foo.first
=> true
```

**Comment by JonLev** [comment]
@EppO thanks, but what I actually want to know is the roles for the given resource. If I can avoid to tests all my role that could be great 😅!

**Comment by EppO** [comment]
In that case, that would be that [one](https://github.com/RolifyCommunity/rolify/wiki/Usage#resource-role-queries).
You need to add `resourcify` to your resource Model. I admit we need to improve the docs on that part, it's something that is being asked frequently.

**Comment by JonLev** [comment]
@EppO yes it's close, but it still miss the part of instance level with the current user.
Dos this work:
```
forum = Forum.first
forum.roles(current_user)
# return the role of current the user for the given resource
```

**Comment by JonLev** [comment]
Okay, after reading the code, I think you can do:
```
forum = Forum.first
forum.roles.joins(:user_roles).where(user_roles: { user_id: current_user.id })
```
Could deserve a method or a wiki 😄.
I close the issue.

**Comment by wayne5540** [comment]
Thanks @JonLev 

I'm also looking for methods like `forum.roles(current_user)` or `User.find(1).role_for(Foo.find(1))`, is it possible we add those APIs into this gem?

How do you think? @EppO
