### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by vfonic** [RolifyCommunity/rolify#523]
I just discovered this repo and it seems like a great functionality that I'm looking for. It looks like there are a lot of open issues and even pull requests. Is this repo still maintained? Do you need help?

**Comment by nfo** [comment]
No idea, I haven't used rolify since 2012.

**Comment by stigi** [comment]
That means it's stable I guess... 

/unsubscribe

**Comment by thomas-mcdonald** [comment]
I'm willing to help maintain if it wouldn't be a solo endeavour - there are a few patches that have not yet had a Rubygems release so we run a vendored version

**Comment by chadwtaylor** [comment]
Our team is ready to dive into this gem but the posting of this issue is giving us a pause. If this is not going to be maintained, is there another/alternative gem that would be good to consider?

**Comment by vfonic** [comment]
I'm also willing to help. Is there someone from the maintainers who we can talk to who would want to either give someone who wants to work on this gem a maintainer access or at least check the PRs (and maybe eventually give maintainer access)?

I see that maintainers are still active and answer to issues from time to time. Let's get the gem active instead of having to fork it.

@chadwtaylor is there any functionality you're missing? I'd suggest you start with this gem, and if something is missing, let's see if we can make a PR and if it doesn't get accepted, maybe someone can create a fork and we can switch to it and keep active development there?

**Comment by chadwtaylor** [comment]
@vfonic Yea, we will likely go ahead and start with this gem. We will see what snags we run into and go from there.

**Comment by thomas-mcdonald** [comment]
Following up here to repeat the offer to help maintain this

**Comment by EppO** [comment]
Hi,
original maintainer of rolify here, sorry for being silent for so long.
@wldcordeiro and I have been busy on other non-ruby fronts for a while now, I'm willing to add new members to @RolifyCommunity/contributors to help maintaining this library, as I see that still many people are using it.
There are couple of challenges that I tried to address last year I couldn't achieve:
- Clean-up test suite
- Support latest version of Mongoid
- Make sure it runs with latest Rails

Anybody willing to help, let me know. 
Thanks for keeping this library alive, really appreciated.

**Comment by ziaulrehman40** [comment]
This gem solves a basic problem in a simple way. I don't see it getting un-relevent in near foreseeable future.

**Comment by thomas-mcdonald** [comment]
Working to get a new release out in the next couple of weeks. We are in a real need of someone who is invested in the MongoDB side of the house and can work to add support for more recent mongoid versions.

**Comment by stevenbuccini** [comment]
@thomas-mcdonald Any update on that major version release? Would help pull in some great performance fixes + Rails 6 support. Happy to help if I can.

**Comment by thomas-mcdonald** [comment]
Pushed v5.3.0 with the current state of master + out of the box support for Rails 6 / Ruby 2.7.

@stevenbuccini will try and review/release the PR you flagged soon but it's a bit more complex than some of the other fixes that were waiting to go, biased towards getting something out today

**Comment by stevenbuccini** [comment]
Thanks @thomas-mcdonald, really appreciate all the time you put into this. Let me know if I can help going forward.
