### ISSUE TITLE
Deprecation warning with Ruby 2.7

### ISSUE THREAD

**Issue by nburt** [RolifyCommunity/rolify#528]
We just upgraded to Ruby 2.7 and are seeing a deprecation warning from Rolify:

`/Users/nateburt/.rvm/gems/ruby-2.7.0/gems/rolify-5.2.0/lib/rolify.rb:30: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

Is there any work planned on this? If not I'm happy to take a stab at it and open up a PR.

**Comment by thomas-mcdonald** [comment]
Hey @nburt - would definitely take a PR for this if you have time!

**Comment by nburt** [comment]
Sounds good. I pulled the repo however was having some trouble with the tests, I followed the readme here: https://github.com/RolifyCommunity/rolify/blob/master/spec/README.rdoc but I'm getting `cannot load such file -- active_record` when running `bundle exec rake` and 435 failures when running `bundle exec rake spec_all`. Any ideas on what I'm missing?

**Comment by thomas-mcdonald** [comment]
I filed #530 to track issues with specs. That documentation appears to be outdated. I'm still ~working on~ discovering what the local dev environment looks like, but `appraisal install` will install the various different combination of gems specified in the Appraisals file, and then something like `ADAPTER=active_record bundle exec appraisal activerecord-4 rake spec` will run the suite with the specific adapter/supporting gems.

**Comment by brian-kephart** [comment]
I'm experiencing this issue on version 5.2.0. The README says the specs are passing now. @nburt do you still have a PR in progress?

**Comment by nburt** [comment]
I haven't had a chance to work on this yet, if you have time go for it. I need to wrap up a feature at work but planning on working on a PR as soon as that is done. Hopefully towards the end of this week

**Comment by nburt** [comment]
Created PR: https://github.com/RolifyCommunity/rolify/pull/541
