### ISSUE TITLE
Does the has_cached_role? caveat in the docs still apply?

### ISSUE THREAD

**Issue by philipbjorge** [RolifyCommunity/rolify#540]
> This method should be used with caution. If you don't preload the roles, the has_cached_role? might return false. In the above example, it would return false for @user.has_cached_role?(:member, Forum), because User.with_role(:admin, Forum) will load only the :admin roles.

Is this still accurate? Can you explain a little bit more about why this occurs?

I'm unable to repro this locally. Is there something off with this sample code?

```
user_test = FactoryBot.create(:user)  # this starts out with a :member role
user_test.add_role :foo, Track
user_test.add_role :bar, Track

users = User.with_role(:foo, Track)
users.each do |user|
  raise "missing :foo role" unless user.has_cached_role? :foo, Track
  raise "missing :bar role" unless user.has_cached_role? :bar, Track
  raise "missing :member role" unless user.has_cached_role? :member
end
```

**Comment by kingp0dd** [comment]
I want to know this too

**Comment by alex-fiennes** [comment]
I would also be keen to know of situations where `has_cached_role?` can return the wrong results.  I have yet to find a situation where this is the case, but I am loath to utilise the functionality without a better understanding of when it fails as currently it doesn't appear to do so.

**Comment by gabrielhilal** [comment]
I implemented the cached roles [looong time ago](https://github.com/RolifyCommunity/rolify/pull/369) after [this discussion](https://github.com/RolifyCommunity/rolify/issues/359). Something changed since 2015 (probably the way Rails would load the associations) and I could not replicate the preload issue anymore.

**Comment by alex-fiennes** [comment]
thank you very much for checking. :-)
