### ISSUE TITLE
rolify.rb:30: warning: Using the last argument as keyword parameters is deprecated

### ISSUE THREAD

**Issue by yshmarov** [RolifyCommunity/rolify#542]
When running commands in the console I get this
`/home/ubuntu/.rvm/gems/ruby-2.7.1/gems/rolify-5.2.0/lib/rolify.rb:30: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

Any idea what to do about it?

Rails 6.0.3
Ruby 2.7.1

**Comment by alaarab** [comment]
I am also getting this issue.

**Comment by ThomasConnolly** [comment]
Me, too

**Comment by alaarab** [comment]
https://github.com/RolifyCommunity/rolify/pull/541 This pull request seems to resolve this issue.

**Comment by thomas-mcdonald** [comment]
Closing as duplicate of #528
