### ISSUE TITLE
[Feature request] Resources with strict role

### ISSUE THREAD

**Issue by gahia** [RolifyCommunity/rolify#554]
Hi!

I have a case where I would like to **enforce only roles scoped to a resource instance** behavior.

Of course I should not grant any user a role scoped to a class but mistakes happen and I think it may be good to add a new feature that works like this:

```
scope.with_strict_role :admin, current_user
# => [ list of Business instances that ONLY have role "admin" bound to them 
# =>  and belong to current_user roles excluding occurrences with no resource_id assigned ]
```

This means, the SQL query should not include the conditions like ` "roles".resource_id IS NULL`

It also may worth to complement the strict mode for resources, that works like this:

```
class Business < ActiveRecord::Base
  resourcify strict: true
end

@user = User.first
@user.add_role(:admin, Business.first)

@user.has_role?(:admin, Business) #=> false
@user.has_role?(:admin, Business.first) #=> true
@user.has_role?(:admin, Business.last) #=> false

@user.add_role(:admin, Business) #=> Exception?
```

This is, in fact, a security enforcement to avoid a role assignment scoped to a class grant some user full access to any instance of that class when that must not happen.

This is just an idea.

Thanks!

**Comment by thomas-mcdonald** [comment]
Can you check out #543 and let me know if it enables what you're after?

**Comment by gahia** [comment]
Hi Thomas!

#543 does enables what I was looking for! The suggestion at the end is something different but I may create a new request only with that.

Thanks!
