### ISSUE TITLE
Broken doc link

### ISSUE THREAD

**Issue by KevinColemanInc** [RolifyCommunity/rolify#561]
Invalid link: https://rolifycommunity.github.com/rolify/
<img width="324" alt="image" src="https://user-images.githubusercontent.com/2381771/116572570-1561cd00-a8da-11eb-8b50-9bfaa801908e.png">

The correct link is:
https://rolifycommunity.github.io/rolify/

**Comment by thomas-mcdonald** [comment]
updated, thanks!
