### ISSUE TITLE
[Request] Release a new version

### ISSUE THREAD

**Issue by v-kumar** [RolifyCommunity/rolify#581]
Would appreciate #575 in a dot release.

**Comment by v-kumar** [comment]
Any update on this @thomas-mcdonald ?

**Comment by tannakartikey** [comment]
Yes, a new release with the patch for #575 would be great. Let me know if any help is needed. Thanks

**Comment by v-kumar** [comment]
Any update on this st all? Coming up on 1- months...

**Comment by krtschmr** [comment]
> Any update on this st all? Coming up on 10 months...

open source development is (sometimes, sadly) dead.

F

**Comment by thomas-mcdonald** [comment]
Took me a while to find my MFA but just pushed 6.0.1

**Comment by krtschmr** [comment]
thank you @thomas-mcdonald !
